[package]
name = "iroha_actor"
version = "2.0.0-pre-rc.5"
authors = ["Iroha 2 team <https://github.com/orgs/soramitsu/teams/iroha2>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
# Enable deadlock detection
deadlock_detection = ["petgraph"]

[dependencies]
iroha_actor_derive = { version = "=2.0.0-pre-rc.5", path = "derive" }
iroha_logger = { version = "=2.0.0-pre-rc.5", path = "../logger" }
iroha_data_primitives = { version = "=2.0.0-pre-rc.5", path = "../data_model/primitives" }

async-trait = "0.1.56"
once_cell = "1.12.0"
dashmap = "5.3.4"
futures = { version = "0.3.21", default-features = false, features = ["std", "async-await"] }
tokio = { version = "1.19.2", features = ["sync", "time", "rt", "rt-multi-thread", "macros"] }
thiserror = "1.0.31"

petgraph = { version = "0.6.2", default-features = false, optional = true }
