[package]
name = "test_network"
version = "2.0.0-pre-rc.5"
authors = ["Iroha 2 team <https://github.com/orgs/soramitsu/teams/iroha2>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
# Enable mock tests
mock = []
# Create a mock query for testing
query = []

[dependencies]
iroha_core = { version = "=2.0.0-pre-rc.5", path = "../../core" }
iroha_client = { version = "=2.0.0-pre-rc.5", path = "../../client" }
iroha_data_model = { version = "=2.0.0-pre-rc.5", path = "../../data_model" }
iroha_logger = { version = "=2.0.0-pre-rc.5", path = "../../logger" }
iroha_actor = { version = "=2.0.0-pre-rc.5", path = "../../actor" }
iroha = { path = "../../cli", features = ["test-network"] }

eyre = "0.6.8"
tempfile = "3.3.0"
unique_port = "0.1.1"
tokio = { version = "1.19.2", features = ["rt", "rt-multi-thread", "macros"] }
rand = "0.8.5"
futures = { version = "0.3.21", default-features = false, features = ["std", "async-await"] }

[dev-dependencies]

async-trait = "0.1.56"
once_cell = "1.12.0"
