[package]
name = "iroha_permissions_validators"
version = "2.0.0-pre-rc.5"
authors = ["Iroha 2 team <https://github.com/orgs/soramitsu/teams/iroha2>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iroha_core = { version = "=2.0.0-pre-rc.5", path = "../core", default-features = false }
iroha_data_model = { version = "=2.0.0-pre-rc.5", path = "../data_model", default-features = false }
iroha_macro = { version = "=2.0.0-pre-rc.5", path = "../macro" }
iroha_schema = { version = "=2.0.0-pre-rc.5", path = "../schema" }

serde = { version = "1.0.137", features = ["derive"] }
parity-scale-codec = { version = "3.1.2", default-features = false, features = ["derive", "full"] }
once_cell = "1.12.0"
thiserror = "1.0.31"

[dev-dependencies]
iroha_data_model = { version = "=2.0.0-pre-rc.5", path = "../data_model", default-features = false }
iroha_core = { version = "=2.0.0-pre-rc.5", path = "../core", default-features = false }
