[package]
name = "iroha_version_derive"
version = "2.0.0-pre-rc.5"
authors = ["Iroha 2 team <https://github.com/orgs/soramitsu/teams/iroha2>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.96", default-features = false, features = ["full"] }
quote = "1.0.18"
proc-macro2 = "1.0.39"
proc-macro-error = "1.0.4"

[dev-dependencies]
iroha_version = { version = "=2.0.0-pre-rc.5", path = "..", features = ["scale", "json"]}
iroha_macro = { version = "=2.0.0-pre-rc.5", path = "../../macro" }

parity-scale-codec = { version = "3.1.2", default-features = false, features = ["derive", "full"] }
serde_json = { version = "1.0.81", default-features = false, features = ["alloc"] }
serde = { version = "1.0.137", default-features = false, features = ["derive"] }

trybuild = "1.0.63"
