[package]
name = "iroha_data_primitives"
version = "2.0.0-pre.1"
authors = ["Iroha 2 team <https://github.com/orgs/soramitsu/teams/iroha2>"]
edition = "2021"
description = "Data primitives used in iroha_data_model."
readme = "README.md"
homepage = "https://github.com/hyperledger/iroha/tree/iroha2-dev"
repository = "https://github.com/hyperledger/iroha/tree/iroha2-dev"
license = "Apache-2.0"
keywords = ["crypto", "blockchain", "ledger", "iroha", "model"]
categories = ["cryptography::cryptocurrencies", "api-bindings"]

[badges]
is-it-maintained-issue-resolution = { repository = "https://github.com/hyperledger/iroha" }
is-it-maintained-open-issues = { repository = "https://github.com/hyperledger/iroha" }
maintenance = { status = "actively-developed" }

[features]
default = ["std"]
std = ["iroha_macro/std", "iroha_version/std", "iroha_version/warp", "iroha_crypto/std", "fixnum/std", "thiserror"]
roles = []

[dependencies]
iroha_crypto = { path = "../../crypto", version = "=2.0.0-pre.1", default-features = false }
iroha_macro = { path = "../../macro", version = "=2.0.0-pre.1", default-features = false }
iroha_schema = { path = "../../schema", version = "=2.0.0-pre.1", default-features = false }
iroha_version = { path = "../../version", version = "=2.0.0-pre.1", default-features = false, features = ["derive", "json", "scale"] }

parity-scale-codec = { version = "2.3.1", default-features = false, features = ["derive"] }
fixnum = { version = "0.6.1", default-features = false, features = ["serde", "parity", "i64"]}
derive_more = { version = "0.99.16", default-features = false, features = ["display"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.59", default-features = false }
warp = { version = "0.3", default-features = false, optional = true }
thiserror = { version = "1.0.28", optional = true }
smallvec = { version = "1.6.1", features = ["serde", "union"] }
smallstr = { version = "0.2.0", features = ["serde", "union"] }
